// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogavnykvdyrnzxezuabo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nYXZueWt2ZHlybnp4ZXp1YWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNzc5NzAsImV4cCI6MjA3MTY1Mzk3MH0.xPvhRieg48iY6vap8m064dw9wTQPLaNBevZuqpcvi0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});